-- GENERATED by npm run db:bundle — do not edit. Run once on a NEW, empty project.

-- ==================== 0001_extensions_and_types.sql ====================
-- =====================================================================
-- Dreamland Rental Management System
-- 0001 — Extensions, schemas and enumerated types
-- See documentation/03_Database_Design.md §2
-- =====================================================================

create extension if not exists pg_trgm with schema extensions;

-- Internal helpers and trigger functions live here. This schema is NOT
-- exposed through the Supabase API, so nothing in it is callable as RPC.
create schema if not exists private;

create type public.user_role     as enum ('owner', 'staff');
create type public.car_status    as enum ('available', 'on_rent', 'maintenance', 'sold');
create type public.rent_period   as enum ('daily', 'weekly', 'monthly', 'yearly');
create type public.rental_status as enum ('out', 'returned', 'closed', 'void');
create type public.payment_type  as enum ('advance', 'rent', 'deposit_taken', 'deposit_used', 'deposit_returned', 'refund');
create type public.fuel_level    as enum ('empty', 'quarter', 'half', 'three_quarter', 'full');


-- ==================== 0002_tables.sql ====================
-- =====================================================================
-- 0002 — Tables
-- See documentation/03_Database_Design.md §3
-- Money: numeric(12,2) PKR. Nothing is ever hard-deleted.
-- =====================================================================

-- ---------------------------------------------------------------------
-- branches (Phase 1 has exactly one; ready for multi-branch)
-- ---------------------------------------------------------------------
create table public.branches (
  id          uuid primary key default gen_random_uuid(),
  name        text not null check (length(trim(name)) between 2 and 80),
  address     text,
  phone       text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- profiles — one row per auth user (created by trigger)
-- ---------------------------------------------------------------------
create table public.profiles (
  id                  uuid primary key references auth.users (id) on delete restrict,
  full_name           text not null check (length(trim(full_name)) between 1 and 80),
  role                public.user_role not null default 'staff',
  is_active           boolean not null default true,
  preferred_language  text not null default 'en' check (preferred_language in ('en', 'ur')),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- cars
-- ---------------------------------------------------------------------
create table public.cars (
  id                     uuid primary key default gen_random_uuid(),
  branch_id              uuid not null default '00000000-0000-0000-0000-000000000001'
                           references public.branches (id),
  car_number             text not null check (car_number ~ '^[A-Za-z0-9 -]{2,20}$'),
  car_number_normalized  text generated always as
                           (upper(regexp_replace(car_number, '[^A-Za-z0-9]', '', 'g'))) stored,
  make                   text check (make is null or length(make) <= 40),
  model                  text not null check (length(trim(model)) between 1 and 60),
  year                   smallint check (year between 1980 and 2100),
  color                  text check (color is null or length(color) <= 30),
  registered_to          text check (registered_to is null or length(registered_to) <= 80),
  standard_rent          numeric(12,2) not null check (standard_rent between 0 and 10000000),
  standard_rent_period   public.rent_period not null default 'monthly',
  insurance_expiry       date,
  status                 public.car_status not null default 'available',
  status_changed_at      timestamptz not null default now(),
  notes                  text,
  archived_at            timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  created_by             uuid default auth.uid() references public.profiles (id),
  updated_by             uuid references public.profiles (id),
  constraint cars_sold_is_archived check (status <> 'sold' or archived_at is not null)
);

-- ---------------------------------------------------------------------
-- customers (drivers)
-- ---------------------------------------------------------------------
create table public.customers (
  id              uuid primary key default gen_random_uuid(),
  full_name       text not null check (length(trim(full_name)) between 2 and 80),
  mobile          text not null check (mobile ~ '^03[0-9]{9}$'),
  license_number  text not null check (length(trim(license_number)) between 3 and 30),
  cnic            text,
  notes           text,
  archived_at     timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  created_by      uuid default auth.uid() references public.profiles (id),
  updated_by      uuid references public.profiles (id)
);

-- ---------------------------------------------------------------------
-- payment_methods (owner-managed list)
-- ---------------------------------------------------------------------
create table public.payment_methods (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique check (code ~ '^[a-z][a-z0-9_]{1,30}$'),
  name        text not null check (length(trim(name)) between 2 and 60),
  is_active   boolean not null default true,
  sort_order  smallint not null default 100,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- rentals
-- ---------------------------------------------------------------------
create sequence public.rental_number_seq;

create table public.rentals (
  id                      uuid primary key default gen_random_uuid(),
  rental_number           text not null unique
                            default ('DR-' || lpad(nextval('public.rental_number_seq')::text, 4, '0')),
  branch_id               uuid not null default '00000000-0000-0000-0000-000000000001'
                            references public.branches (id),
  car_id                  uuid not null references public.cars (id),
  customer_id             uuid not null references public.customers (id),

  -- driver snapshot (copied at Car Out; rule R-10)
  driver_name             text not null check (length(trim(driver_name)) between 2 and 80),
  driver_mobile           text not null check (driver_mobile ~ '^03[0-9]{9}$'),
  driver_license          text not null check (length(trim(driver_license)) between 3 and 30),

  -- guarantor (required; rule R-9)
  guarantor_name          text not null check (length(trim(guarantor_name)) between 2 and 80),
  guarantor_mobile        text not null check (guarantor_mobile ~ '^03[0-9]{9}$'),

  -- dates
  out_at                  timestamptz not null,
  expected_return_date    date not null,
  returned_at             timestamptz,
  payment_due_date        date,                 -- next payment due (rule P-9)
  payment_due_amount      numeric(12,2) check (payment_due_amount is null or payment_due_amount > 0),

  -- kilometers & fuel (all optional)
  start_km                integer check (start_km >= 0),
  end_km                  integer check (end_km >= 0),
  fuel_out                public.fuel_level,
  fuel_in                 public.fuel_level,

  -- rent values
  rental_type             public.rent_period not null,
  standard_rent_snapshot  numeric(12,2),
  agreed_rate             numeric(12,2) not null check (agreed_rate between 0 and 10000000),
  rent_amount             numeric(12,2) not null check (rent_amount between 0 and 100000000),

  -- charges
  fuel_charge             numeric(12,2) not null default 0 check (fuel_charge between 0 and 10000000),
  damage_charge           numeric(12,2) not null default 0 check (damage_charge between 0 and 10000000),
  damage_notes            text,
  extra_km_charge         numeric(12,2) not null default 0 check (extra_km_charge between 0 and 10000000),
  other_charge            numeric(12,2) not null default 0 check (other_charge between 0 and 10000000),
  other_charge_note       text,
  total_bill              numeric(14,2) generated always as
                            (rent_amount + fuel_charge + damage_charge + extra_km_charge + other_charge) stored,

  -- status
  status                  public.rental_status not null default 'out',
  closed_at               timestamptz,
  notes                   text,
  void_reason             text,
  voided_at               timestamptz,
  voided_by               uuid references public.profiles (id),

  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),
  created_by              uuid default auth.uid() references public.profiles (id),
  updated_by              uuid references public.profiles (id),

  constraint rentals_km_order        check (end_km is null or start_km is null or end_km >= start_km),
  constraint rentals_return_after_out check (returned_at is null or returned_at >= out_at),
  constraint rentals_expected_after_out
    check (expected_return_date >= (out_at at time zone 'Asia/Karachi')::date),
  constraint rentals_returned_has_date
    check (status not in ('returned', 'closed') or returned_at is not null),
  constraint rentals_other_charge_note
    check (other_charge = 0 or length(trim(coalesce(other_charge_note, ''))) > 0),
  constraint rentals_void_reason     check (status <> 'void' or void_reason is not null)
);

-- ---------------------------------------------------------------------
-- payments
-- ---------------------------------------------------------------------
create table public.payments (
  id            uuid primary key default gen_random_uuid(),
  rental_id     uuid not null references public.rentals (id),
  payment_date  date not null,
  amount        numeric(12,2) not null check (amount > 0 and amount <= 100000000),
  type          public.payment_type not null,
  method_id     uuid references public.payment_methods (id),
  reference     text check (reference is null or length(reference) <= 80),
  notes         text,
  is_voided     boolean not null default false,
  void_reason   text,
  voided_at     timestamptz,
  voided_by     uuid references public.profiles (id),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  created_by    uuid default auth.uid() references public.profiles (id),
  updated_by    uuid references public.profiles (id),

  -- "Deposit used" is an internal transfer: no method. Everything else needs one.
  constraint payments_method_rule check ((type = 'deposit_used') = (method_id is null)),
  constraint payments_void_reason check (not is_voided or void_reason is not null)
);

-- ---------------------------------------------------------------------
-- sold_cars
-- ---------------------------------------------------------------------
create table public.sold_cars (
  id            uuid primary key default gen_random_uuid(),
  car_id        uuid not null unique references public.cars (id),
  sale_date     date not null,
  sale_price    numeric(12,2) not null check (sale_price between 0 and 1000000000),
  buyer_name    text not null check (length(trim(buyer_name)) between 2 and 80),
  buyer_mobile  text check (buyer_mobile is null or buyer_mobile ~ '^03[0-9]{9}$'),
  buyer_cnic    text,
  notes         text,
  created_at    timestamptz not null default now(),
  created_by    uuid default auth.uid() references public.profiles (id)
);

-- ---------------------------------------------------------------------
-- car_status_history
-- ---------------------------------------------------------------------
create table public.car_status_history (
  id           bigint generated always as identity primary key,
  car_id       uuid not null references public.cars (id),
  from_status  public.car_status,
  to_status    public.car_status not null,
  reason       text,
  rental_id    uuid references public.rentals (id),
  changed_by   uuid references public.profiles (id),
  changed_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- audit_log (append-only)
-- ---------------------------------------------------------------------
create table public.audit_log (
  id          bigint generated always as identity primary key,
  table_name  text not null,
  record_id   uuid not null,
  action      text not null,
  old_data    jsonb,
  new_data    jsonb,
  reason      text,
  changed_by  uuid references public.profiles (id),
  changed_at  timestamptz not null default now()
);


-- ==================== 0003_indexes.sql ====================
-- =====================================================================
-- 0003 — Indexes and unique rules
-- See documentation/03_Database_Design.md §5
-- =====================================================================

-- Car number unique ignoring spaces / dashes / case (rule V-1)
create unique index cars_car_number_uq on public.cars (car_number_normalized);
create index cars_active_status_idx   on public.cars (status) where archived_at is null;
create index cars_insurance_idx       on public.cars (insurance_expiry);

-- One active customer per mobile number (decision Q6)
create unique index customers_mobile_active_uq on public.customers (mobile) where archived_at is null;
create index customers_name_trgm_idx on public.customers
  using gin (lower(full_name) extensions.gin_trgm_ops);

-- A car can never have two active rentals (rule R-8)
create unique index rentals_one_active_per_car_uq on public.rentals (car_id) where status = 'out';
create index rentals_car_idx        on public.rentals (car_id, out_at desc);
create index rentals_customer_idx   on public.rentals (customer_id, out_at desc);
create index rentals_status_idx     on public.rentals (status);
create index rentals_due_idx        on public.rentals (payment_due_date) where status in ('out', 'returned');

create index payments_rental_idx    on public.payments (rental_id);
create index payments_date_idx      on public.payments (payment_date);
create index payments_income_idx    on public.payments (type, payment_date) where not is_voided;

create index car_status_history_car_idx on public.car_status_history (car_id, changed_at desc);
create index audit_log_record_idx       on public.audit_log (table_name, record_id, changed_at desc);
create index audit_log_changed_at_idx   on public.audit_log (changed_at desc);


-- ==================== 0004_helpers_and_triggers.sql ====================
-- =====================================================================
-- 0004 — Helper functions and triggers
--   * auth / role helpers used by RLS and RPC functions
--   * timestamps (updated_at / updated_by)
--   * mobile number normalization (rule V-5)
--   * car status guard + status history (rules C-3 … C-9)
--   * audit log (NFR-05)
--   * profile creation for new auth users
-- =====================================================================

-- ---------------------------------------------------------------------
-- Auth / role helpers
-- ---------------------------------------------------------------------
create or replace function private.is_active_user()
returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and is_active);
$$;

create or replace function private.is_owner()
returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and is_active and role = 'owner');
$$;

create or replace function private.require_active()
returns void
language plpgsql stable security definer set search_path = public, pg_temp
as $$
begin
  if not private.is_active_user() then
    raise exception 'You are not signed in or your account is disabled' using errcode = '42501';
  end if;
end;
$$;

create or replace function private.require_owner()
returns void
language plpgsql stable security definer set search_path = public, pg_temp
as $$
begin
  if not private.is_owner() then
    raise exception 'Only the owner can do this' using errcode = '42501';
  end if;
end;
$$;

-- "Today" in Pakistan time — used for all date rules and alerts
create or replace function private.today_pkt()
returns date
language sql stable
as $$
  select (now() at time zone 'Asia/Karachi')::date;
$$;

create or replace function private.pkt_date(p_ts timestamptz)
returns date
language sql immutable
as $$
  select (p_ts at time zone 'Asia/Karachi')::date;
$$;

-- Format money for error messages: 45000 -> "Rs 45,000"
create or replace function private.rs(p_amount numeric)
returns text
language sql immutable
as $$
  select 'Rs ' || trim(to_char(round(p_amount), 'FM999,999,999,990'));
$$;

-- ---------------------------------------------------------------------
-- Mobile normalization: accepts 03XXXXXXXXX, 3XXXXXXXXX, 923XXXXXXXXX,
-- +92 3XX XXXXXXX, 0300-1234567 … and stores 03XXXXXXXXX (rule V-5)
-- ---------------------------------------------------------------------
create or replace function private.normalize_mobile(p text)
returns text
language plpgsql immutable
as $$
declare
  v text := regexp_replace(coalesce(p, ''), '\D', '', 'g');
begin
  if v ~ '^92[0-9]{10}$' then
    v := '0' || substr(v, 3);
  elsif v ~ '^3[0-9]{9}$' then
    v := '0' || v;
  end if;
  if v !~ '^03[0-9]{9}$' then
    raise exception 'Invalid mobile number "%". Use the format 03XXXXXXXXX', p using errcode = '22023';
  end if;
  return v;
end;
$$;

create or replace function private.trg_normalize_customer_mobile()
returns trigger language plpgsql as $$
begin
  new.mobile := private.normalize_mobile(new.mobile);
  return new;
end;
$$;

create or replace function private.trg_normalize_rental_mobiles()
returns trigger language plpgsql as $$
begin
  new.driver_mobile    := private.normalize_mobile(new.driver_mobile);
  new.guarantor_mobile := private.normalize_mobile(new.guarantor_mobile);
  return new;
end;
$$;

create or replace function private.trg_normalize_buyer_mobile()
returns trigger language plpgsql as $$
begin
  if nullif(trim(coalesce(new.buyer_mobile, '')), '') is null then
    new.buyer_mobile := null;
  else
    new.buyer_mobile := private.normalize_mobile(new.buyer_mobile);
  end if;
  return new;
end;
$$;

create trigger customers_normalize_mobile
  before insert or update of mobile on public.customers
  for each row execute function private.trg_normalize_customer_mobile();

create trigger rentals_normalize_mobiles
  before insert or update of driver_mobile, guarantor_mobile on public.rentals
  for each row execute function private.trg_normalize_rental_mobiles();

create trigger sold_cars_normalize_mobile
  before insert or update of buyer_mobile on public.sold_cars
  for each row execute function private.trg_normalize_buyer_mobile();

-- ---------------------------------------------------------------------
-- Timestamps
-- ---------------------------------------------------------------------
create or replace function private.trg_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- For tables that also track who made the change
create or replace function private.trg_set_updated_by()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  new.updated_by := auth.uid();
  return new;
end;
$$;

create trigger branches_updated        before update on public.branches        for each row execute function private.trg_set_updated_at();
create trigger profiles_updated        before update on public.profiles        for each row execute function private.trg_set_updated_at();
create trigger payment_methods_updated before update on public.payment_methods for each row execute function private.trg_set_updated_at();
create trigger cars_updated            before update on public.cars            for each row execute function private.trg_set_updated_by();
create trigger customers_updated       before update on public.customers       for each row execute function private.trg_set_updated_by();
create trigger rentals_updated         before update on public.rentals         for each row execute function private.trg_set_updated_by();
create trigger payments_updated        before update on public.payments        for each row execute function private.trg_set_updated_by();

-- ---------------------------------------------------------------------
-- Transaction-local context used by business functions to pass a
-- reason / action / rental into the audit and status-history triggers.
-- ---------------------------------------------------------------------
create or replace function private.set_ctx(p_action text default null, p_reason text default null, p_rental_id uuid default null)
returns void language plpgsql as $$
begin
  perform set_config('app.audit_action', coalesce(p_action, ''), true);
  perform set_config('app.audit_reason', coalesce(p_reason, ''), true);
  perform set_config('app.rental_id',    coalesce(p_rental_id::text, ''), true);
end;
$$;

create or replace function private.clear_ctx()
returns void language plpgsql as $$
begin
  perform private.set_ctx(null, null, null);
end;
$$;

-- ---------------------------------------------------------------------
-- Car status guard (rules C-3 … C-8)
-- Clients cannot update cars.status at all (column privileges, 0007);
-- this trigger additionally guarantees only legal transitions happen,
-- even from inside business functions.
-- ---------------------------------------------------------------------
create or replace function private.trg_cars_guard()
returns trigger language plpgsql as $$
begin
  if old.status = 'sold' then
    raise exception 'Sold cars are archived and cannot be changed' using errcode = '23514';
  end if;

  if new.status is distinct from old.status then
    if not (
         (old.status = 'available'   and new.status in ('on_rent', 'maintenance', 'sold'))
      or (old.status = 'maintenance' and new.status in ('available', 'sold'))
      or (old.status = 'on_rent'     and new.status in ('available', 'maintenance'))
    ) then
      raise exception 'A car cannot change from % to %', old.status, new.status using errcode = '23514';
    end if;
    new.status_changed_at := now();
  end if;
  return new;
end;
$$;

create trigger cars_guard before update on public.cars
  for each row execute function private.trg_cars_guard();

create or replace function private.trg_cars_status_history()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if tg_op = 'INSERT' then
    insert into public.car_status_history (car_id, from_status, to_status, reason, changed_by)
    values (new.id, null, new.status, 'Car added', auth.uid());
  elsif new.status is distinct from old.status then
    insert into public.car_status_history (car_id, from_status, to_status, reason, rental_id, changed_by)
    values (
      new.id, old.status, new.status,
      nullif(current_setting('app.audit_reason', true), ''),
      nullif(current_setting('app.rental_id', true), '')::uuid,
      auth.uid()
    );
  end if;
  return new;
end;
$$;

create trigger cars_status_history after insert or update of status on public.cars
  for each row execute function private.trg_cars_status_history();

-- ---------------------------------------------------------------------
-- Audit log (append-only)
-- ---------------------------------------------------------------------
create or replace function private.trg_audit()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_old jsonb := case when tg_op = 'UPDATE' then to_jsonb(old) end;
  v_new jsonb := to_jsonb(new);
begin
  -- Skip no-op updates (only timestamps changed)
  if tg_op = 'UPDATE'
     and (v_old - 'updated_at' - 'updated_by') = (v_new - 'updated_at' - 'updated_by') then
    return new;
  end if;

  insert into public.audit_log (table_name, record_id, action, old_data, new_data, reason, changed_by)
  values (
    tg_table_name,
    (v_new ->> 'id')::uuid,
    coalesce(nullif(current_setting('app.audit_action', true), ''), lower(tg_op)),
    v_old,
    v_new,
    nullif(current_setting('app.audit_reason', true), ''),
    auth.uid()
  );
  return new;
end;
$$;

create trigger cars_audit      after insert or update on public.cars      for each row execute function private.trg_audit();
create trigger customers_audit after insert or update on public.customers for each row execute function private.trg_audit();
create trigger rentals_audit   after insert or update on public.rentals   for each row execute function private.trg_audit();
create trigger payments_audit  after insert or update on public.payments  for each row execute function private.trg_audit();
create trigger sold_cars_audit after insert or update on public.sold_cars for each row execute function private.trg_audit();
create trigger profiles_audit  after update on public.profiles            for each row execute function private.trg_audit();
create trigger payment_methods_audit after insert or update on public.payment_methods for each row execute function private.trg_audit();

-- ---------------------------------------------------------------------
-- New auth user -> profile. The very first user becomes the owner;
-- everyone after that starts as staff (the owner can promote them).
-- ---------------------------------------------------------------------
create or replace function private.handle_new_user()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), split_part(new.email, '@', 1)),
    case when exists (select 1 from public.profiles where role = 'owner') then 'staff' else 'owner' end::public.user_role
  );
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users
  for each row execute function private.handle_new_user();


-- ==================== 0005_views.sql ====================
-- =====================================================================
-- 0005 — Calculation views
-- See documentation/05_Business_Rules.md §3–§6 and 03_Database_Design.md §4
--
-- All money numbers shown anywhere in the app come from these views,
-- so the dashboard, rental screens and reports always agree.
-- security_invoker = true -> the caller's RLS applies.
-- =====================================================================

-- ---------------------------------------------------------------------
-- rental_balances — one row per rental (including void; consumers
-- exclude status = 'void' from totals).
--   Paid     = advance + rent + deposit_used − refund        (rule P-2)
--   Pending  = total_bill − paid                             (rule P-3)
--   Deposit  = taken − returned − used                       (rule D-2)
-- ---------------------------------------------------------------------
create view public.rental_balances with (security_invoker = true) as
with pay as (
  select
    rental_id,
    coalesce(sum(amount) filter (where type = 'advance'), 0)          as advance_paid,
    coalesce(sum(amount) filter (where type = 'rent'), 0)             as rent_paid,
    coalesce(sum(amount) filter (where type = 'deposit_used'), 0)     as deposit_used,
    coalesce(sum(amount) filter (where type = 'refund'), 0)           as refunded,
    coalesce(sum(amount) filter (where type = 'deposit_taken'), 0)    as deposit_taken,
    coalesce(sum(amount) filter (where type = 'deposit_returned'), 0) as deposit_returned,
    max(payment_date) filter (where type in ('advance', 'rent'))      as last_payment_date
  from public.payments
  where not is_voided
  group by rental_id
),
base as (
  select
    r.id, r.rental_number, r.branch_id, r.status,
    r.car_id, c.car_number, c.make as car_make, c.model as car_model, c.color as car_color,
    r.customer_id, r.driver_name, r.driver_mobile, r.driver_license,
    r.guarantor_name, r.guarantor_mobile,
    r.rental_type, r.agreed_rate, r.standard_rent_snapshot,
    r.out_at, r.expected_return_date, r.returned_at, r.closed_at,
    r.payment_due_date, r.payment_due_amount,
    r.start_km, r.end_km, r.fuel_out, r.fuel_in,
    r.rent_amount, r.fuel_charge, r.damage_charge, r.damage_notes,
    r.extra_km_charge, r.other_charge, r.other_charge_note, r.total_bill,
    r.notes, r.void_reason, r.voided_at, r.created_at, r.updated_at,
    coalesce(p.advance_paid, 0)     as advance_paid,
    coalesce(p.rent_paid, 0)        as rent_paid,
    coalesce(p.deposit_used, 0)     as deposit_used,
    coalesce(p.refunded, 0)         as refunded,
    coalesce(p.deposit_taken, 0)    as deposit_taken,
    coalesce(p.deposit_returned, 0) as deposit_returned,
    p.last_payment_date
  from public.rentals r
  join public.cars c on c.id = r.car_id
  left join pay p on p.rental_id = r.id
),
calc as (
  select
    b.*,
    b.advance_paid + b.rent_paid + b.deposit_used - b.refunded                 as total_paid,
    b.total_bill - (b.advance_paid + b.rent_paid + b.deposit_used - b.refunded) as pending,
    b.deposit_taken - b.deposit_returned - b.deposit_used                       as deposit_balance,
    private.today_pkt()                                                         as today
  from base b
)
select
  c.id, c.rental_number, c.branch_id, c.status,
  c.car_id, c.car_number, c.car_make, c.car_model, c.car_color,
  c.customer_id, c.driver_name, c.driver_mobile, c.driver_license,
  c.guarantor_name, c.guarantor_mobile,
  c.rental_type, c.agreed_rate, c.standard_rent_snapshot,
  c.out_at, c.expected_return_date, c.returned_at, c.closed_at,
  c.payment_due_date, c.payment_due_amount,
  c.start_km, c.end_km, c.fuel_out, c.fuel_in,
  c.rent_amount, c.fuel_charge, c.damage_charge, c.damage_notes,
  c.extra_km_charge, c.other_charge, c.other_charge_note, c.total_bill,
  c.notes, c.void_reason, c.voided_at, c.created_at, c.updated_at,
  c.advance_paid, c.rent_paid, c.deposit_used, c.refunded,
  c.deposit_taken, c.deposit_returned, c.last_payment_date,
  c.total_paid, c.pending, c.deposit_balance,
  (c.pending = 0 and c.deposit_balance = 0) as is_settled,
  -- Amount due by payment_due_date (whole pending when no due amount set)
  case when c.pending > 0 then least(coalesce(c.payment_due_amount, c.pending), c.pending) else 0 end
    as due_amount,
  -- Alert flags (rules A-1 … A-7)
  (c.status in ('out', 'returned') and c.pending > 0
     and c.payment_due_date < c.today)                                     as is_payment_overdue,
  (c.status in ('out', 'returned') and c.pending > 0
     and c.payment_due_date between c.today and c.today + 3)               as is_payment_due_soon,
  (c.status = 'out' and c.expected_return_date < c.today)                  as is_return_overdue,
  (c.status in ('out', 'returned') and c.pending < 0)                      as is_overpaid,
  case when c.payment_due_date < c.today then c.today - c.payment_due_date else 0 end
    as days_payment_overdue,
  case when c.status = 'out' and c.expected_return_date < c.today
       then c.today - c.expected_return_date else 0 end                   as days_return_overdue
from calc c;

-- ---------------------------------------------------------------------
-- rental_alerts — one row per active alert on a rental
-- ---------------------------------------------------------------------
create view public.rental_alerts with (security_invoker = true) as
select
  rb.id as rental_id, rb.rental_number, rb.status as rental_status,
  rb.car_id, rb.car_number, rb.car_model,
  rb.customer_id, rb.driver_name, rb.driver_mobile,
  rb.pending, rb.deposit_balance,
  a.alert_type, a.severity, a.amount, a.days, a.ref_date,
  a.sort_rank
from public.rental_balances rb
cross join lateral (
  values
    ('payment_overdue',  'red',   rb.due_amount,        rb.days_payment_overdue,                  rb.payment_due_date,     1,
       rb.is_payment_overdue),
    ('return_overdue',   'red',   null::numeric,        rb.days_return_overdue,                   rb.expected_return_date, 2,
       rb.is_return_overdue),
    ('overpaid',         'red',   -rb.pending,          null::integer,                            null::date,              3,
       rb.is_overpaid),
    ('payment_pending',  'red',   greatest(rb.pending, 0), null::integer,                         rb.returned_at::date,    4,
       rb.status = 'returned' and (rb.pending > 0 or rb.deposit_balance > 0) and not rb.is_payment_overdue),
    ('payment_due_soon', 'amber', rb.due_amount,        (rb.payment_due_date - private.today_pkt()), rb.payment_due_date, 5,
       rb.is_payment_due_soon)
) as a (alert_type, severity, amount, days, ref_date, sort_rank, active)
where a.active and rb.status in ('out', 'returned');

-- ---------------------------------------------------------------------
-- car_alerts — insurance expiring (≤ 30 days) / expired (rules A-5, A-6)
-- ---------------------------------------------------------------------
create view public.car_alerts with (security_invoker = true) as
select
  c.id as car_id, c.car_number, c.make, c.model, c.status,
  case when c.insurance_expiry < private.today_pkt() then 'insurance_expired' else 'insurance_expiring' end as alert_type,
  case when c.insurance_expiry < private.today_pkt() then 'red' else 'amber' end as severity,
  c.insurance_expiry,
  (c.insurance_expiry - private.today_pkt()) as days_left
from public.cars c
where c.status <> 'sold'
  and c.archived_at is null
  and c.insurance_expiry is not null
  and c.insurance_expiry <= private.today_pkt() + 30;

-- ---------------------------------------------------------------------
-- income_ledger — payments that count as income, cash basis (rule P-7)
--   advance, rent, deposit_used  -> +amount
--   refund                       -> −amount
--   deposit_taken / returned     -> not income
-- ---------------------------------------------------------------------
create view public.income_ledger with (security_invoker = true) as
select
  p.id as payment_id,
  p.payment_date,
  p.type,
  case when p.type = 'refund' then -p.amount else p.amount end as amount,
  pm.name as method_name,
  p.method_id,
  r.id as rental_id, r.rental_number,
  r.car_id, c.car_number, c.model as car_model,
  r.customer_id, r.driver_name,
  r.branch_id
from public.payments p
join public.rentals r on r.id = p.rental_id
join public.cars c on c.id = r.car_id
left join public.payment_methods pm on pm.id = p.method_id
where not p.is_voided
  and r.status <> 'void'
  and p.type in ('advance', 'rent', 'deposit_used', 'refund');

-- ---------------------------------------------------------------------
-- payment_list — every payment with context (payment history report)
-- ---------------------------------------------------------------------
create view public.payment_list with (security_invoker = true) as
select
  p.id, p.rental_id, p.payment_date, p.amount, p.type, p.method_id,
  pm.name as method_name, p.reference, p.notes,
  p.is_voided, p.void_reason, p.voided_at,
  p.created_at, p.updated_at, p.created_by, p.updated_by,
  (p.updated_at > p.created_at + interval '1 second') as is_edited,
  cp.full_name as created_by_name,
  r.rental_number, r.status as rental_status,
  r.car_id, c.car_number, c.model as car_model,
  r.customer_id, r.driver_name
from public.payments p
join public.rentals r on r.id = p.rental_id
join public.cars c on c.id = r.car_id
left join public.payment_methods pm on pm.id = p.method_id
left join public.profiles cp on cp.id = p.created_by;

-- ---------------------------------------------------------------------
-- dashboard_summary — single row
-- ---------------------------------------------------------------------
create view public.dashboard_summary with (security_invoker = true) as
select
  (select count(*) from public.cars where archived_at is null and status = 'available')   as available_count,
  (select count(*) from public.cars where archived_at is null and status = 'on_rent')     as on_rent_count,
  (select count(*) from public.cars where archived_at is null and status = 'maintenance') as maintenance_count,
  (select count(*) from public.cars where archived_at is null and status <> 'sold')       as active_car_count,
  (select coalesce(sum(greatest(pending, 0)), 0) from public.rental_balances
     where status in ('out', 'returned'))                                                 as total_outstanding,
  (select coalesce(sum(due_amount), 0) from public.rental_balances
     where is_payment_overdue)                                                            as total_overdue,
  (select coalesce(sum(deposit_balance), 0) from public.rental_balances
     where status in ('out', 'returned'))                                                 as deposits_held,
  (select coalesce(sum(amount), 0) from public.income_ledger
     where payment_date >= date_trunc('week', private.today_pkt())::date)                 as income_this_week,
  (select coalesce(sum(amount), 0) from public.income_ledger
     where payment_date >= date_trunc('month', private.today_pkt())::date)                as income_this_month;

-- ---------------------------------------------------------------------
-- car_earnings — lifetime totals per car
-- ---------------------------------------------------------------------
create view public.car_earnings with (security_invoker = true) as
select
  c.id as car_id, c.car_number, c.make, c.model, c.status, c.archived_at,
  count(rb.id) filter (where rb.status <> 'void')                                      as rentals_count,
  coalesce(sum(rb.total_bill) filter (where rb.status <> 'void'), 0)                   as total_billed,
  coalesce(sum(rb.total_paid) filter (where rb.status <> 'void'), 0)                   as total_received,
  coalesce(sum(greatest(rb.pending, 0)) filter (where rb.status in ('out', 'returned')), 0) as total_pending,
  max(rb.out_at) filter (where rb.status <> 'void')                                    as last_rented_at
from public.cars c
left join public.rental_balances rb on rb.car_id = c.id
group by c.id;

-- ---------------------------------------------------------------------
-- customer_balances — totals per customer (pending by customer report)
-- ---------------------------------------------------------------------
create view public.customer_balances with (security_invoker = true) as
select
  cu.id as customer_id, cu.full_name, cu.mobile, cu.license_number, cu.archived_at,
  count(rb.id) filter (where rb.status <> 'void')                                      as rentals_count,
  count(rb.id) filter (where rb.status = 'out')                                        as active_rentals_count,
  coalesce(sum(rb.total_bill) filter (where rb.status <> 'void'), 0)                   as total_billed,
  coalesce(sum(rb.total_paid) filter (where rb.status <> 'void'), 0)                   as total_paid,
  coalesce(sum(greatest(rb.pending, 0)) filter (where rb.status in ('out', 'returned')), 0) as total_pending,
  coalesce(sum(rb.due_amount) filter (where rb.is_payment_overdue), 0)                 as total_overdue,
  coalesce(sum(rb.deposit_balance) filter (where rb.status in ('out', 'returned')), 0) as deposit_held,
  max(rb.out_at) filter (where rb.status <> 'void')                                    as last_rental_at
from public.customers cu
left join public.rental_balances rb on rb.customer_id = cu.id
group by cu.id;

-- ---------------------------------------------------------------------
-- car_list — cars with their current rental (for list screens)
-- ---------------------------------------------------------------------
create view public.car_list with (security_invoker = true) as
select
  c.*,
  ar.id as active_rental_id, ar.rental_number as active_rental_number,
  ar.driver_name as active_driver_name, ar.expected_return_date as active_expected_return_date,
  (select h.reason from public.car_status_history h
     where h.car_id = c.id order by h.changed_at desc, h.id desc limit 1) as last_status_reason
from public.cars c
left join public.rentals ar on ar.car_id = c.id and ar.status = 'out';


-- ==================== 0006_business_functions.sql ====================
-- =====================================================================
-- 0006 — Business actions (RPC functions)
-- See documentation/02_System_Architecture.md §3.1 and 05_Business_Rules.md
--
-- Every multi-step action runs in ONE transaction. Clients cannot write
-- rentals / payments / car status directly (0007); they must call these.
-- All functions: SECURITY DEFINER, fixed search_path, explicit role check.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Internal: current money totals for a rental (non-voided payments)
-- ---------------------------------------------------------------------
create or replace function private.rental_totals(
  p_rental_id uuid,
  out total_bill numeric, out total_paid numeric, out pending numeric, out deposit_balance numeric
)
language sql stable security definer set search_path = public, pg_temp
as $$
  with p as (
    select
      coalesce(sum(case when type in ('advance', 'rent', 'deposit_used') then amount
                        when type = 'refund' then -amount else 0 end), 0) as paid,
      coalesce(sum(case when type = 'deposit_taken' then amount
                        when type in ('deposit_returned', 'deposit_used') then -amount else 0 end), 0) as dep
    from public.payments
    where rental_id = p_rental_id and not is_voided
  )
  select r.total_bill, p.paid, r.total_bill - p.paid, p.dep
  from public.rentals r cross join p
  where r.id = p_rental_id;
$$;

-- ---------------------------------------------------------------------
-- Internal: Returned <-> Closed automatically (rules R-4, R-5)
-- ---------------------------------------------------------------------
create or replace function private.recalc_rental_status(p_rental_id uuid)
returns public.rental_status
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_status public.rental_status;
  t record;
begin
  select status into v_status from public.rentals where id = p_rental_id for update;
  if v_status in ('returned', 'closed') then
    select * into t from private.rental_totals(p_rental_id);
    if t.pending = 0 and t.deposit_balance = 0 then
      update public.rentals set status = 'closed', closed_at = coalesce(closed_at, now())
        where id = p_rental_id and status <> 'closed';
      v_status := 'closed';
    else
      update public.rentals set status = 'returned', closed_at = null
        where id = p_rental_id and status <> 'returned';
      v_status := 'returned';
    end if;
  end if;
  return v_status;
end;
$$;

-- ---------------------------------------------------------------------
-- Internal: money invariants after a payment change.
-- A change may not make things WORSE past the limit (so a correction
-- that improves an already-bad state is still allowed).
--   * deposit balance never below 0                       (D-4, D-5, D-6)
--   * advance / rent / deposit_used never push pending < 0 (P-4, D-4)
--   * refund only up to the overpaid amount               (P-4)
-- ---------------------------------------------------------------------
create or replace function private.assert_money_rules(
  p_type public.payment_type,
  p_before_pending numeric, p_before_deposit numeric,
  p_after_pending numeric,  p_after_deposit numeric
)
returns void
language plpgsql immutable
as $$
begin
  if p_after_deposit < 0 and p_after_deposit < p_before_deposit then
    raise exception 'Not enough deposit held. Available deposit: %', private.rs(greatest(p_before_deposit, 0))
      using errcode = '23514';
  end if;
  if p_type in ('advance', 'rent', 'deposit_used') and p_after_pending < 0 and p_after_pending < p_before_pending then
    raise exception 'Amount is more than the pending balance. Maximum allowed: %', private.rs(greatest(p_before_pending, 0))
      using errcode = '23514';
  end if;
  if p_type = 'refund' and p_after_pending > 0 and p_after_pending > p_before_pending then
    raise exception 'A refund is only allowed for an overpaid amount. Maximum refund: %', private.rs(greatest(-p_before_pending, 0))
      using errcode = '23514';
  end if;
end;
$$;

-- ---------------------------------------------------------------------
-- Internal: validate method + date for a payment
-- ---------------------------------------------------------------------
create or replace function private.check_payment_fields(
  p_rental_id uuid, p_type public.payment_type, p_method_id uuid, p_payment_date date, p_allow_inactive_method uuid default null
)
returns void
language plpgsql stable security definer set search_path = public, pg_temp
as $$
declare
  v_out_date date;
begin
  if p_type = 'deposit_used' then
    if p_method_id is not null then
      raise exception '"Deposit used" does not take a payment method' using errcode = '22023';
    end if;
  else
    if p_method_id is null then
      raise exception 'Payment method is required' using errcode = '22023';
    end if;
    if not exists (select 1 from public.payment_methods
                   where id = p_method_id and (is_active or id = p_allow_inactive_method)) then
      raise exception 'Payment method is not available' using errcode = '22023';
    end if;
  end if;

  if p_payment_date is null then
    raise exception 'Payment date is required' using errcode = '22023';
  end if;
  if p_payment_date > private.today_pkt() then
    raise exception 'Payment date cannot be in the future' using errcode = '22023';
  end if;
  select private.pkt_date(out_at) into v_out_date from public.rentals where id = p_rental_id;
  if p_payment_date < v_out_date then
    raise exception 'Payment date cannot be before the rental out date (%)', to_char(v_out_date, 'DD Mon YYYY')
      using errcode = '22023';
  end if;
end;
$$;

-- ---------------------------------------------------------------------
-- Internal: insert a payment with all checks (used by car_out,
-- car_return and record_payment)
-- ---------------------------------------------------------------------
create or replace function private.add_payment(
  p_rental_id uuid, p_type public.payment_type, p_amount numeric, p_payment_date date,
  p_method_id uuid, p_reference text, p_notes text
)
returns uuid
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_status public.rental_status;
  b record;
  a record;
  v_id uuid;
begin
  select status into v_status from public.rentals where id = p_rental_id for update;
  if not found then
    raise exception 'Rental not found' using errcode = 'P0002';
  end if;
  if v_status not in ('out', 'returned') then
    raise exception 'Payments can only be added to rentals that are Out or Returned (this one is %)', v_status
      using errcode = '23514';
  end if;
  if coalesce(p_amount, 0) <= 0 then
    raise exception 'Amount must be more than 0' using errcode = '22023';
  end if;

  perform private.check_payment_fields(p_rental_id, p_type, p_method_id, p_payment_date);

  select * into b from private.rental_totals(p_rental_id);

  insert into public.payments (rental_id, payment_date, amount, type, method_id, reference, notes)
  values (p_rental_id, p_payment_date, round(p_amount, 2), p_type, p_method_id,
          nullif(trim(coalesce(p_reference, '')), ''), nullif(trim(coalesce(p_notes, '')), ''))
  returning id into v_id;

  select * into a from private.rental_totals(p_rental_id);
  perform private.assert_money_rules(p_type, b.pending, b.deposit_balance, a.pending, a.deposit_balance);
  return v_id;
end;
$$;

-- =====================================================================
-- PUBLIC RPC FUNCTIONS
-- =====================================================================

-- ---------------------------------------------------------------------
-- car_out — Flow 2
-- ---------------------------------------------------------------------
create or replace function public.car_out(
  p_car_id               uuid,
  p_driver_name          text,
  p_driver_mobile        text,
  p_driver_license       text,
  p_guarantor_name       text,
  p_guarantor_mobile     text,
  p_rental_type          public.rent_period,
  p_agreed_rate          numeric,
  p_rent_amount          numeric,
  p_expected_return_date date,
  p_customer_id          uuid default null,
  p_out_at               timestamptz default null,
  p_payment_due_date     date default null,
  p_payment_due_amount   numeric default null,
  p_start_km             integer default null,
  p_fuel_out             public.fuel_level default null,
  p_notes                text default null,
  p_advance_amount       numeric default 0,
  p_advance_method_id    uuid default null,
  p_deposit_amount       numeric default 0,
  p_deposit_method_id    uuid default null
)
returns uuid
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_car        public.cars%rowtype;
  v_out_at     timestamptz := coalesce(p_out_at, now());
  v_out_date   date;
  v_mobile     text;
  v_customer   uuid;
  v_rental_id  uuid;
  v_number     text;
  v_due_date   date;
begin
  perform private.require_active();

  -- Lock the car so two users cannot send it out at the same moment
  select * into v_car from public.cars where id = p_car_id for update;
  if not found then
    raise exception 'Car not found' using errcode = 'P0002';
  end if;
  if v_car.status <> 'available' or v_car.archived_at is not null then
    raise exception 'Car % is no longer available', v_car.car_number using errcode = '23514';
  end if;

  if v_out_at > now() + interval '5 minutes' then
    raise exception 'Out date/time cannot be in the future' using errcode = '22023';
  end if;
  v_out_date := private.pkt_date(v_out_at);
  if p_expected_return_date is null or p_expected_return_date < v_out_date then
    raise exception 'Expected return date must be on or after the out date' using errcode = '22023';
  end if;

  v_mobile := private.normalize_mobile(p_driver_mobile);

  -- Customer: use the given one, or find by mobile, or create (decision Q6)
  if p_customer_id is not null then
    if exists (select 1 from public.customers
               where mobile = v_mobile and archived_at is null and id <> p_customer_id) then
      raise exception 'Mobile number % already belongs to another customer', v_mobile using errcode = '23505';
    end if;
    update public.customers
       set full_name = trim(p_driver_name), mobile = v_mobile, license_number = trim(p_driver_license)
     where id = p_customer_id and archived_at is null
    returning id into v_customer;
    if v_customer is null then
      raise exception 'Customer not found' using errcode = 'P0002';
    end if;
  else
    select id into v_customer from public.customers where mobile = v_mobile and archived_at is null;
    if v_customer is null then
      insert into public.customers (full_name, mobile, license_number)
      values (trim(p_driver_name), v_mobile, trim(p_driver_license))
      returning id into v_customer;
    else
      update public.customers
         set full_name = trim(p_driver_name), license_number = trim(p_driver_license)
       where id = v_customer;
    end if;
  end if;

  -- Next payment due (rule P-9)
  v_due_date := coalesce(
    p_payment_due_date,
    case when p_rental_type in ('daily', 'weekly') then p_expected_return_date
         else least((v_out_date + interval '1 month')::date, p_expected_return_date) end
  );

  insert into public.rentals (
    car_id, customer_id, branch_id,
    driver_name, driver_mobile, driver_license,
    guarantor_name, guarantor_mobile,
    out_at, expected_return_date, payment_due_date, payment_due_amount,
    start_km, fuel_out,
    rental_type, standard_rent_snapshot, agreed_rate, rent_amount,
    status, notes
  ) values (
    p_car_id, v_customer, v_car.branch_id,
    trim(p_driver_name), v_mobile, trim(p_driver_license),
    trim(p_guarantor_name), p_guarantor_mobile,
    v_out_at, p_expected_return_date, v_due_date, p_payment_due_amount,
    p_start_km, p_fuel_out,
    p_rental_type, v_car.standard_rent, p_agreed_rate, p_rent_amount,
    'out', nullif(trim(coalesce(p_notes, '')), '')
  )
  returning id, rental_number into v_rental_id, v_number;

  perform private.set_ctx(null, 'Car Out ' || v_number, v_rental_id);
  update public.cars set status = 'on_rent' where id = p_car_id;
  perform private.clear_ctx();

  if coalesce(p_advance_amount, 0) > 0 then
    perform private.add_payment(v_rental_id, 'advance', p_advance_amount, least(v_out_date, private.today_pkt()),
                                p_advance_method_id, null, 'Advance at Car Out');
  end if;
  if coalesce(p_deposit_amount, 0) > 0 then
    perform private.add_payment(v_rental_id, 'deposit_taken', p_deposit_amount, least(v_out_date, private.today_pkt()),
                                p_deposit_method_id, null, 'Deposit at Car Out');
  end if;

  return v_rental_id;
end;
$$;

-- ---------------------------------------------------------------------
-- car_return — Flow 3
-- ---------------------------------------------------------------------
create or replace function public.car_return(
  p_rental_id                 uuid,
  p_returned_at               timestamptz default null,
  p_end_km                    integer default null,
  p_fuel_in                   public.fuel_level default null,
  p_rent_amount               numeric default null,
  p_fuel_charge               numeric default 0,
  p_damage_charge             numeric default 0,
  p_damage_notes              text default null,
  p_extra_km_charge           numeric default 0,
  p_other_charge              numeric default 0,
  p_other_charge_note         text default null,
  p_next_car_status           public.car_status default 'available',
  p_car_status_reason         text default null,
  p_deposit_used              numeric default 0,
  p_payment_amount            numeric default 0,
  p_payment_method_id         uuid default null,
  p_deposit_returned          numeric default 0,
  p_deposit_return_method_id  uuid default null,
  p_notes                     text default null
)
returns public.rental_status
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_r            public.rentals%rowtype;
  v_returned_at  timestamptz := coalesce(p_returned_at, now());
  v_pay_date     date;
begin
  perform private.require_active();

  select * into v_r from public.rentals where id = p_rental_id for update;
  if not found then
    raise exception 'Rental not found' using errcode = 'P0002';
  end if;
  if v_r.status <> 'out' then
    raise exception 'Only a rental that is Out can be returned (this one is %)', v_r.status using errcode = '23514';
  end if;
  if p_next_car_status not in ('available', 'maintenance') then
    raise exception 'After return the car must be Available or At Maintenance' using errcode = '22023';
  end if;
  if v_returned_at > now() + interval '5 minutes' then
    raise exception 'Return date/time cannot be in the future' using errcode = '22023';
  end if;
  if v_returned_at < v_r.out_at then
    raise exception 'Return date/time cannot be before the out date/time' using errcode = '22023';
  end if;
  if p_end_km is not null and v_r.start_km is not null and p_end_km < v_r.start_km then
    raise exception 'End KM (%) cannot be less than start KM (%)', p_end_km, v_r.start_km using errcode = '22023';
  end if;

  perform private.set_ctx('return', null, p_rental_id);
  update public.rentals set
    returned_at       = v_returned_at,
    end_km            = p_end_km,
    fuel_in           = p_fuel_in,
    rent_amount       = coalesce(p_rent_amount, rent_amount),
    fuel_charge       = coalesce(p_fuel_charge, 0),
    damage_charge     = coalesce(p_damage_charge, 0),
    damage_notes      = nullif(trim(coalesce(p_damage_notes, '')), ''),
    extra_km_charge   = coalesce(p_extra_km_charge, 0),
    other_charge      = coalesce(p_other_charge, 0),
    other_charge_note = nullif(trim(coalesce(p_other_charge_note, '')), ''),
    notes             = coalesce(nullif(trim(coalesce(p_notes, '')), ''), notes),
    status            = 'returned'
  where id = p_rental_id;

  perform private.set_ctx(null,
    coalesce(nullif(trim(coalesce(p_car_status_reason, '')), ''), 'Car Return ' || v_r.rental_number),
    p_rental_id);
  update public.cars set status = p_next_car_status where id = v_r.car_id;
  perform private.clear_ctx();

  v_pay_date := least(private.pkt_date(v_returned_at), private.today_pkt());

  -- Settle now (optional): use deposit, take payment, return deposit
  if coalesce(p_deposit_used, 0) > 0 then
    perform private.add_payment(p_rental_id, 'deposit_used', p_deposit_used, v_pay_date, null, null, 'Deposit used at return');
  end if;
  if coalesce(p_payment_amount, 0) > 0 then
    perform private.add_payment(p_rental_id, 'rent', p_payment_amount, v_pay_date, p_payment_method_id, null, 'Payment at return');
  end if;
  if coalesce(p_deposit_returned, 0) > 0 then
    perform private.add_payment(p_rental_id, 'deposit_returned', p_deposit_returned, v_pay_date,
                                p_deposit_return_method_id, null, 'Deposit returned');
  end if;

  return private.recalc_rental_status(p_rental_id);
end;
$$;

-- ---------------------------------------------------------------------
-- record_payment — Flow 4a (optionally sets the next due date, P-9)
-- ---------------------------------------------------------------------
create or replace function public.record_payment(
  p_rental_id        uuid,
  p_type             public.payment_type,
  p_amount           numeric,
  p_payment_date     date default null,
  p_method_id        uuid default null,
  p_reference        text default null,
  p_notes            text default null,
  p_next_due_date    date default null,
  p_next_due_amount  numeric default null
)
returns uuid
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_id uuid;
begin
  perform private.require_active();
  v_id := private.add_payment(p_rental_id, p_type, p_amount, coalesce(p_payment_date, private.today_pkt()),
                              p_method_id, p_reference, p_notes);
  if p_next_due_date is not null then
    update public.rentals
       set payment_due_date = p_next_due_date, payment_due_amount = p_next_due_amount
     where id = p_rental_id;
  end if;
  perform private.recalc_rental_status(p_rental_id);
  return v_id;
end;
$$;

-- ---------------------------------------------------------------------
-- update_payment — Flow 4b (all users, reason required, audited; P-8)
-- Type cannot change: void and re-enter instead.
-- ---------------------------------------------------------------------
create or replace function public.update_payment(
  p_payment_id    uuid,
  p_amount        numeric,
  p_payment_date  date,
  p_method_id     uuid,
  p_reference     text,
  p_notes         text,
  p_reason        text
)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_p       public.payments%rowtype;
  v_status  public.rental_status;
  b record;
  a record;
begin
  perform private.require_active();
  if length(trim(coalesce(p_reason, ''))) < 5 then
    raise exception 'Please give a reason for the change (at least 5 characters)' using errcode = '22023';
  end if;

  select * into v_p from public.payments where id = p_payment_id for update;
  if not found then
    raise exception 'Payment not found' using errcode = 'P0002';
  end if;
  if v_p.is_voided then
    raise exception 'A voided payment cannot be edited' using errcode = '23514';
  end if;
  select status into v_status from public.rentals where id = v_p.rental_id for update;
  if v_status = 'void' then
    raise exception 'Payments of a void rental cannot be edited' using errcode = '23514';
  end if;
  if coalesce(p_amount, 0) <= 0 then
    raise exception 'Amount must be more than 0' using errcode = '22023';
  end if;

  perform private.check_payment_fields(v_p.rental_id, v_p.type, p_method_id, p_payment_date, v_p.method_id);

  select * into b from private.rental_totals(v_p.rental_id);

  perform private.set_ctx('update', trim(p_reason), v_p.rental_id);
  update public.payments set
    amount       = round(p_amount, 2),
    payment_date = p_payment_date,
    method_id    = p_method_id,
    reference    = nullif(trim(coalesce(p_reference, '')), ''),
    notes        = nullif(trim(coalesce(p_notes, '')), '')
  where id = p_payment_id;
  perform private.clear_ctx();

  select * into a from private.rental_totals(v_p.rental_id);
  perform private.assert_money_rules(v_p.type, b.pending, b.deposit_balance, a.pending, a.deposit_balance);
  perform private.recalc_rental_status(v_p.rental_id);
end;
$$;

-- ---------------------------------------------------------------------
-- void_payment — Flow 4c (owner only)
-- ---------------------------------------------------------------------
create or replace function public.void_payment(p_payment_id uuid, p_reason text)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_p public.payments%rowtype;
  b record;
  a record;
begin
  perform private.require_owner();
  if length(trim(coalesce(p_reason, ''))) < 5 then
    raise exception 'Please give a reason for voiding (at least 5 characters)' using errcode = '22023';
  end if;

  select * into v_p from public.payments where id = p_payment_id for update;
  if not found then
    raise exception 'Payment not found' using errcode = 'P0002';
  end if;
  if v_p.is_voided then
    raise exception 'This payment is already voided' using errcode = '23514';
  end if;
  perform 1 from public.rentals where id = v_p.rental_id for update;

  select * into b from private.rental_totals(v_p.rental_id);

  perform private.set_ctx('void', trim(p_reason), v_p.rental_id);
  update public.payments set
    is_voided = true, void_reason = trim(p_reason), voided_at = now(), voided_by = auth.uid()
  where id = p_payment_id;
  perform private.clear_ctx();

  select * into a from private.rental_totals(v_p.rental_id);
  if a.deposit_balance < 0 and a.deposit_balance < b.deposit_balance then
    raise exception 'Voiding this would make the deposit balance negative. Void the "deposit used/returned" entries first'
      using errcode = '23514';
  end if;
  perform private.recalc_rental_status(v_p.rental_id);
end;
$$;

-- ---------------------------------------------------------------------
-- set_next_payment_due — rule P-9 (null amount = whole pending is due)
-- ---------------------------------------------------------------------
create or replace function public.set_next_payment_due(p_rental_id uuid, p_due_date date, p_due_amount numeric default null)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_status public.rental_status;
begin
  perform private.require_active();
  select status into v_status from public.rentals where id = p_rental_id for update;
  if not found then
    raise exception 'Rental not found' using errcode = 'P0002';
  end if;
  if v_status not in ('out', 'returned') then
    raise exception 'Due dates can only be set on rentals that are Out or Returned' using errcode = '23514';
  end if;
  if p_due_amount is not null and p_due_amount <= 0 then
    raise exception 'Due amount must be more than 0' using errcode = '22023';
  end if;
  update public.rentals set payment_due_date = p_due_date, payment_due_amount = p_due_amount
   where id = p_rental_id;
end;
$$;

-- ---------------------------------------------------------------------
-- update_rental — corrections and extensions (rule R-12), audited.
-- NULL parameter = keep current value.
-- ---------------------------------------------------------------------
create or replace function public.update_rental(
  p_rental_id             uuid,
  p_reason                text,
  p_expected_return_date  date default null,
  p_agreed_rate           numeric default null,
  p_rent_amount           numeric default null,
  p_fuel_charge           numeric default null,
  p_damage_charge         numeric default null,
  p_damage_notes          text default null,
  p_extra_km_charge       numeric default null,
  p_other_charge          numeric default null,
  p_other_charge_note     text default null,
  p_start_km              integer default null,
  p_end_km                integer default null,
  p_fuel_out              public.fuel_level default null,
  p_fuel_in               public.fuel_level default null,
  p_returned_at           timestamptz default null,
  p_guarantor_name        text default null,
  p_guarantor_mobile      text default null,
  p_notes                 text default null
)
returns public.rental_status
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_r public.rentals%rowtype;
begin
  perform private.require_active();
  if length(trim(coalesce(p_reason, ''))) < 5 then
    raise exception 'Please give a reason for the change (at least 5 characters)' using errcode = '22023';
  end if;

  select * into v_r from public.rentals where id = p_rental_id for update;
  if not found then
    raise exception 'Rental not found' using errcode = 'P0002';
  end if;
  if v_r.status = 'void' then
    raise exception 'A void rental cannot be changed' using errcode = '23514';
  end if;
  if v_r.status = 'out' and (p_returned_at is not null or p_end_km is not null or p_fuel_in is not null) then
    raise exception 'Return details can only be set by returning the car' using errcode = '23514';
  end if;
  if p_returned_at is not null and p_returned_at > now() + interval '5 minutes' then
    raise exception 'Return date/time cannot be in the future' using errcode = '22023';
  end if;

  perform private.set_ctx('update', trim(p_reason), p_rental_id);
  update public.rentals set
    expected_return_date = coalesce(p_expected_return_date, expected_return_date),
    agreed_rate          = coalesce(p_agreed_rate, agreed_rate),
    rent_amount          = coalesce(p_rent_amount, rent_amount),
    fuel_charge          = coalesce(p_fuel_charge, fuel_charge),
    damage_charge        = coalesce(p_damage_charge, damage_charge),
    damage_notes         = coalesce(p_damage_notes, damage_notes),
    extra_km_charge      = coalesce(p_extra_km_charge, extra_km_charge),
    other_charge         = coalesce(p_other_charge, other_charge),
    other_charge_note    = coalesce(p_other_charge_note, other_charge_note),
    start_km             = coalesce(p_start_km, start_km),
    end_km               = coalesce(p_end_km, end_km),
    fuel_out             = coalesce(p_fuel_out, fuel_out),
    fuel_in              = coalesce(p_fuel_in, fuel_in),
    returned_at          = coalesce(p_returned_at, returned_at),
    guarantor_name       = coalesce(nullif(trim(coalesce(p_guarantor_name, '')), ''), guarantor_name),
    guarantor_mobile     = coalesce(nullif(trim(coalesce(p_guarantor_mobile, '')), ''), guarantor_mobile),
    notes                = coalesce(p_notes, notes)
  where id = p_rental_id;
  perform private.clear_ctx();

  return private.recalc_rental_status(p_rental_id);
end;
$$;

-- ---------------------------------------------------------------------
-- set_car_maintenance — Flow 1b (Available <-> At Maintenance only)
-- ---------------------------------------------------------------------
create or replace function public.set_car_maintenance(p_car_id uuid, p_to_maintenance boolean, p_reason text default null)
returns public.car_status
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_status public.car_status;
  v_target public.car_status := case when p_to_maintenance then 'maintenance' else 'available' end;
begin
  perform private.require_active();
  select status into v_status from public.cars where id = p_car_id for update;
  if not found then
    raise exception 'Car not found' using errcode = 'P0002';
  end if;
  if p_to_maintenance and v_status <> 'available' then
    raise exception 'Only an Available car can be sent to maintenance' using errcode = '23514';
  end if;
  if not p_to_maintenance and v_status <> 'maintenance' then
    raise exception 'Only a car At Maintenance can be marked Available' using errcode = '23514';
  end if;

  perform private.set_ctx(null,
    coalesce(nullif(trim(coalesce(p_reason, '')), ''),
             case when p_to_maintenance then 'Sent to maintenance' else 'Back from maintenance' end),
    null);
  update public.cars set status = v_target where id = p_car_id;
  perform private.clear_ctx();
  return v_target;
end;
$$;

-- ---------------------------------------------------------------------
-- sell_car — Flow 5 (owner only). Sold is final and archived.
-- ---------------------------------------------------------------------
create or replace function public.sell_car(
  p_car_id        uuid,
  p_sale_date     date,
  p_sale_price    numeric,
  p_buyer_name    text,
  p_buyer_mobile  text default null,
  p_buyer_cnic    text default null,
  p_notes         text default null
)
returns uuid
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_car public.cars%rowtype;
  v_id  uuid;
begin
  perform private.require_owner();
  select * into v_car from public.cars where id = p_car_id for update;
  if not found then
    raise exception 'Car not found' using errcode = 'P0002';
  end if;
  if v_car.status = 'sold' then
    raise exception 'This car is already sold' using errcode = '23514';
  end if;
  if v_car.status = 'on_rent' then
    raise exception 'Car % is On Rent. Return the car first', v_car.car_number using errcode = '23514';
  end if;
  if p_sale_date is null or p_sale_date > private.today_pkt() then
    raise exception 'Sale date is required and cannot be in the future' using errcode = '22023';
  end if;
  if p_sale_price is null or p_sale_price < 0 then
    raise exception 'Sale price is required' using errcode = '22023';
  end if;

  insert into public.sold_cars (car_id, sale_date, sale_price, buyer_name, buyer_mobile, buyer_cnic, notes)
  values (p_car_id, p_sale_date, p_sale_price, trim(p_buyer_name), p_buyer_mobile,
          nullif(trim(coalesce(p_buyer_cnic, '')), ''), nullif(trim(coalesce(p_notes, '')), ''))
  returning id into v_id;

  perform private.set_ctx('sell', 'Sold to ' || trim(p_buyer_name), null);
  update public.cars set status = 'sold', archived_at = coalesce(archived_at, now()) where id = p_car_id;
  perform private.clear_ctx();
  return v_id;
end;
$$;

-- ---------------------------------------------------------------------
-- void_rental — Flow 6 (owner only; data-entry mistakes)
-- ---------------------------------------------------------------------
create or replace function public.void_rental(p_rental_id uuid, p_reason text)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_r public.rentals%rowtype;
begin
  perform private.require_owner();
  if length(trim(coalesce(p_reason, ''))) < 5 then
    raise exception 'Please give a reason for voiding (at least 5 characters)' using errcode = '22023';
  end if;
  select * into v_r from public.rentals where id = p_rental_id for update;
  if not found then
    raise exception 'Rental not found' using errcode = 'P0002';
  end if;
  if v_r.status = 'void' then
    raise exception 'This rental is already void' using errcode = '23514';
  end if;
  if exists (select 1 from public.payments where rental_id = p_rental_id and not is_voided) then
    raise exception 'Void all payments of this rental first' using errcode = '23514';
  end if;

  if v_r.status = 'out' then
    perform private.set_ctx(null, 'Rental ' || v_r.rental_number || ' voided', p_rental_id);
    update public.cars set status = 'available' where id = v_r.car_id and status = 'on_rent';
  end if;

  perform private.set_ctx('void', trim(p_reason), p_rental_id);
  update public.rentals set
    status = 'void', void_reason = trim(p_reason), voided_at = now(), voided_by = auth.uid(), closed_at = null
  where id = p_rental_id;
  perform private.clear_ctx();
end;
$$;

-- ---------------------------------------------------------------------
-- archive_car / restore_car (owner only) — retire a car without selling
-- ---------------------------------------------------------------------
create or replace function public.archive_car(p_car_id uuid, p_reason text)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_car public.cars%rowtype;
begin
  perform private.require_owner();
  select * into v_car from public.cars where id = p_car_id for update;
  if not found then
    raise exception 'Car not found' using errcode = 'P0002';
  end if;
  if v_car.status in ('on_rent', 'sold') then
    raise exception 'Cars that are On Rent or Sold cannot be archived' using errcode = '23514';
  end if;
  if v_car.archived_at is not null then
    raise exception 'Car is already archived' using errcode = '23514';
  end if;
  perform private.set_ctx('archive', nullif(trim(coalesce(p_reason, '')), ''), null);
  update public.cars set archived_at = now() where id = p_car_id;
  perform private.clear_ctx();
end;
$$;

create or replace function public.restore_car(p_car_id uuid)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
begin
  perform private.require_owner();
  perform private.set_ctx('restore', null, null);
  update public.cars set archived_at = null where id = p_car_id and status <> 'sold' and archived_at is not null;
  if not found then
    raise exception 'Car cannot be restored' using errcode = '23514';
  end if;
  perform private.clear_ctx();
end;
$$;

-- ---------------------------------------------------------------------
-- archive_customer / restore_customer (owner only)
-- ---------------------------------------------------------------------
create or replace function public.archive_customer(p_customer_id uuid, p_reason text default null)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
begin
  perform private.require_owner();
  if exists (select 1 from public.rentals where customer_id = p_customer_id and status = 'out') then
    raise exception 'This customer has a car out. Return it first' using errcode = '23514';
  end if;
  perform private.set_ctx('archive', nullif(trim(coalesce(p_reason, '')), ''), null);
  update public.customers set archived_at = now() where id = p_customer_id and archived_at is null;
  if not found then
    raise exception 'Customer not found or already archived' using errcode = 'P0002';
  end if;
  perform private.clear_ctx();
end;
$$;

create or replace function public.restore_customer(p_customer_id uuid)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_mobile text;
begin
  perform private.require_owner();
  select mobile into v_mobile from public.customers where id = p_customer_id and archived_at is not null;
  if not found then
    raise exception 'Customer not found or not archived' using errcode = 'P0002';
  end if;
  if exists (select 1 from public.customers where mobile = v_mobile and archived_at is null) then
    raise exception 'Another active customer already uses mobile %', v_mobile using errcode = '23505';
  end if;
  perform private.set_ctx('restore', null, null);
  update public.customers set archived_at = null where id = p_customer_id;
  perform private.clear_ctx();
end;
$$;

-- ---------------------------------------------------------------------
-- set_user_access — owner changes a user's role / active flag
-- ---------------------------------------------------------------------
create or replace function public.set_user_access(p_user_id uuid, p_role public.user_role, p_is_active boolean)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
begin
  perform private.require_owner();
  if p_user_id = auth.uid() and (p_role <> 'owner' or not p_is_active) then
    raise exception 'You cannot remove your own owner access' using errcode = '23514';
  end if;
  update public.profiles set role = p_role, is_active = p_is_active where id = p_user_id;
  if not found then
    raise exception 'User not found' using errcode = 'P0002';
  end if;
end;
$$;


-- ==================== 0007_security.sql ====================
-- =====================================================================
-- 0007 — Row Level Security, privileges
-- See documentation/03_Database_Design.md §7
--
-- Model:
--   * anon (not logged in)  -> nothing at all
--   * authenticated         -> read everything IF profile is active
--                              write only the columns listed below
--   * rentals, payments, sold_cars, car status, history, audit
--                           -> only through the SECURITY DEFINER
--                              functions in 0006
--   * DELETE                -> nobody, on any table
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Start from zero
-- ---------------------------------------------------------------------
revoke all on all tables    in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
revoke all on all functions in schema public from public, anon, authenticated;
revoke all on all functions in schema private from public, anon, authenticated;

-- Supabase grants new objects to anon/authenticated by default; stop that
-- for objects created by later migrations.
alter default privileges in schema public revoke all on tables    from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;
alter default privileges in schema public revoke all on functions from public, anon, authenticated;

-- ---------------------------------------------------------------------
-- 2. Enable RLS on every table
-- ---------------------------------------------------------------------
alter table public.branches           enable row level security;
alter table public.profiles           enable row level security;
alter table public.cars               enable row level security;
alter table public.car_status_history enable row level security;
alter table public.customers          enable row level security;
alter table public.payment_methods    enable row level security;
alter table public.rentals            enable row level security;
alter table public.payments           enable row level security;
alter table public.sold_cars          enable row level security;
alter table public.audit_log          enable row level security;

-- ---------------------------------------------------------------------
-- 3. Helpers used inside policies / views
-- ---------------------------------------------------------------------
grant usage on schema private to authenticated;
grant execute on function private.is_active_user() to authenticated;
grant execute on function private.is_owner()       to authenticated;
grant execute on function private.today_pkt()      to authenticated;

-- ---------------------------------------------------------------------
-- 4. Read access (tables + views) for authenticated; RLS filters rows
-- ---------------------------------------------------------------------
grant select on all tables in schema public to authenticated;

create policy "active users read"  on public.branches           for select to authenticated using (private.is_active_user());
create policy "active users read"  on public.cars               for select to authenticated using (private.is_active_user());
create policy "active users read"  on public.car_status_history for select to authenticated using (private.is_active_user());
create policy "active users read"  on public.customers          for select to authenticated using (private.is_active_user());
create policy "active users read"  on public.payment_methods    for select to authenticated using (private.is_active_user());
create policy "active users read"  on public.rentals            for select to authenticated using (private.is_active_user());
create policy "active users read"  on public.payments           for select to authenticated using (private.is_active_user());
create policy "active users read"  on public.sold_cars          for select to authenticated using (private.is_active_user());
create policy "active users read"  on public.audit_log          for select to authenticated using (private.is_active_user());

-- A disabled user can still read their OWN profile (to show "Account disabled")
create policy "read own or active" on public.profiles for select to authenticated
  using (id = auth.uid() or private.is_active_user());

-- ---------------------------------------------------------------------
-- 5. Direct writes (column-limited)
-- ---------------------------------------------------------------------

-- cars: details only. status / archived_at / created_by are NOT writable.
grant insert (car_number, make, model, year, color, registered_to,
              standard_rent, standard_rent_period, insurance_expiry, notes)
  on public.cars to authenticated;
grant update (car_number, make, model, year, color, registered_to,
              standard_rent, standard_rent_period, insurance_expiry, notes)
  on public.cars to authenticated;

create policy "active users add cars" on public.cars for insert to authenticated
  with check (private.is_active_user());
create policy "active users edit unsold cars" on public.cars for update to authenticated
  using (private.is_active_user() and status <> 'sold')
  with check (private.is_active_user());

-- customers
grant insert (full_name, mobile, license_number, cnic, notes) on public.customers to authenticated;
grant update (full_name, mobile, license_number, cnic, notes) on public.customers to authenticated;

create policy "active users add customers" on public.customers for insert to authenticated
  with check (private.is_active_user());
create policy "active users edit customers" on public.customers for update to authenticated
  using (private.is_active_user()) with check (private.is_active_user());

-- rentals: only free-text notes directly; everything else via functions
grant update (notes) on public.rentals to authenticated;
create policy "active users edit rental notes" on public.rentals for update to authenticated
  using (private.is_active_user()) with check (private.is_active_user());

-- profiles: own name / language only (role & active via set_user_access)
grant update (full_name, preferred_language) on public.profiles to authenticated;
create policy "edit own profile" on public.profiles for update to authenticated
  using (id = auth.uid() and private.is_active_user())
  with check (id = auth.uid());

-- payment_methods: owner manages the list
grant insert (code, name, is_active, sort_order) on public.payment_methods to authenticated;
grant update (name, is_active, sort_order)       on public.payment_methods to authenticated;
create policy "owner adds methods" on public.payment_methods for insert to authenticated
  with check (private.is_owner());
create policy "owner edits methods" on public.payment_methods for update to authenticated
  using (private.is_owner()) with check (private.is_owner());

-- branches: read only in Phase 1

-- No policy or privilege for: INSERT/UPDATE on payments, sold_cars,
-- car_status_history, audit_log; INSERT on rentals; DELETE anywhere.

-- ---------------------------------------------------------------------
-- 6. RPC functions callable by logged-in users (each checks role itself)
-- ---------------------------------------------------------------------
grant execute on function public.car_out(uuid, text, text, text, text, text, public.rent_period, numeric, numeric, date,
                                         uuid, timestamptz, date, numeric, integer, public.fuel_level, text,
                                         numeric, uuid, numeric, uuid) to authenticated;
grant execute on function public.car_return(uuid, timestamptz, integer, public.fuel_level, numeric, numeric, numeric, text,
                                            numeric, numeric, text, public.car_status, text, numeric, numeric, uuid,
                                            numeric, uuid, text) to authenticated;
grant execute on function public.record_payment(uuid, public.payment_type, numeric, date, uuid, text, text, date, numeric) to authenticated;
grant execute on function public.update_payment(uuid, numeric, date, uuid, text, text, text) to authenticated;
grant execute on function public.void_payment(uuid, text) to authenticated;
grant execute on function public.set_next_payment_due(uuid, date, numeric) to authenticated;
grant execute on function public.update_rental(uuid, text, date, numeric, numeric, numeric, numeric, text, numeric, numeric, text,
                                               integer, integer, public.fuel_level, public.fuel_level, timestamptz, text, text, text) to authenticated;
grant execute on function public.set_car_maintenance(uuid, boolean, text) to authenticated;
grant execute on function public.sell_car(uuid, date, numeric, text, text, text, text) to authenticated;
grant execute on function public.void_rental(uuid, text) to authenticated;
grant execute on function public.archive_car(uuid, text) to authenticated;
grant execute on function public.restore_car(uuid) to authenticated;
grant execute on function public.archive_customer(uuid, text) to authenticated;
grant execute on function public.restore_customer(uuid) to authenticated;
grant execute on function public.set_user_access(uuid, public.user_role, boolean) to authenticated;


-- ==================== 0008_seed.sql ====================
-- =====================================================================
-- 0008 — Reference data
-- =====================================================================

insert into public.branches (id, name, address)
values ('00000000-0000-0000-0000-000000000001', 'Dreamland – Aari Syedan', 'Aari Syedan, Islamabad, Pakistan')
on conflict (id) do nothing;

insert into public.payment_methods (code, name, sort_order) values
  ('cash',          'Cash',                                 10),
  ('bank_transfer', 'Bank Transfer',                        20),
  ('mobile_wallet', 'Mobile Wallet (JazzCash / Easypaisa)', 30)
on conflict (code) do nothing;
